
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abdel
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        try {
            Image img = ImageIO.read(getClass().getResource("/images/hospital.png"));
            this.setIconImage(img);
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        connect();
    }
Connection con;
PreparedStatement pst;
ResultSet rs;

public void connect(){
    
        String currentdir=System.getProperty("user.dir");
            try {
                Class.forName("org.h2.Driver");
            con= DriverManager.getConnection("jdbc:h2:"+currentdir+"\\hms_db\\HMS","","");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtutype = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Creation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Black", 1, 24))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("UserName");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("UserType");

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });

        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameKeyPressed(evt);
            }
        });

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpassword.setToolTipText("");
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });

        txtutype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtutype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pharmacist", "Doctor", "Receptionist" }));
        txtutype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtutypeKeyPressed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtutype, javax.swing.GroupLayout.Alignment.LEADING, 0, 208, Short.MAX_VALUE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtutype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            String name = txtname.getText();
            String username = txtusername.getText();
            String password =Arrays.toString(txtpassword.getPassword());
            String usertype = txtutype.getSelectedItem().toString();
            
            
            try {
                PreparedStatement check = con.prepareStatement("select * from users where name=? and username=? and password=? and utype=?"); 
                check.setString(1,name);
                check.setString(2,username);
                check.setString(3,password);
                check.setString(4,usertype);
                rs = check.executeQuery(); 
                 if (rs.next()) { 
                    JOptionPane.showMessageDialog(this,"user already exists");
                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                         } 
                 else {
                    pst=con.prepareStatement("insert into users(name,username,password,utype)values(?,?,?,?)");
                    pst.setString(1,name);
                    pst.setString(2,username);
                    pst.setString(3,password);
                    pst.setString(4,usertype);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"user added successfully");

                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                    this.setVisible(false);
                    new login().setVisible(true);
                     }
        } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
            
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
            String name = txtname.getText();
            String username = txtusername.getText();
            String password =Arrays.toString(txtpassword.getPassword());
            String usertype = txtutype.getSelectedItem().toString();
            
            if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            try {
                PreparedStatement check = con.prepareStatement("select * from users where name=? and username=? and password=? and utype=?"); 
                check.setString(1,name);
                check.setString(2,username);
                check.setString(3,password);
                check.setString(4,usertype);
                rs = check.executeQuery(); 
                 if (rs.next()) { 
                    JOptionPane.showMessageDialog(this,"user already exists");
                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                         } 
                 else {
                    pst=con.prepareStatement("insert into users(name,username,password,utype)values(?,?,?,?)");
                    pst.setString(1,name);
                    pst.setString(2,username);
                    pst.setString(3,password);
                    pst.setString(4,usertype);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"user added successfully");

                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                    this.setVisible(false);
                    new login().setVisible(true);
                     }
        } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyPressed
 String name = txtname.getText();
            String username = txtusername.getText();
            String password =Arrays.toString(txtpassword.getPassword());
            String usertype = txtutype.getSelectedItem().toString();
            
            if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            try {
                PreparedStatement check = con.prepareStatement("select * from users where name=? and username=? and password=? and utype=?"); 
                check.setString(1,name);
                check.setString(2,username);
                check.setString(3,password);
                check.setString(4,usertype);
                rs = check.executeQuery(); 
                 if (rs.next()) { 
                    JOptionPane.showMessageDialog(this,"user already exists");
                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                         } 
                 else {
                    pst=con.prepareStatement("insert into users(name,username,password,utype)values(?,?,?,?)");
                    pst.setString(1,name);
                    pst.setString(2,username);
                    pst.setString(3,password);
                    pst.setString(4,usertype);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"user added successfully");

                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                    this.setVisible(false);
                    new login().setVisible(true);
                     }
        } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_txtusernameKeyPressed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
 String name = txtname.getText();
            String username = txtusername.getText();
            String password =Arrays.toString(txtpassword.getPassword());
            String usertype = txtutype.getSelectedItem().toString();
            
            if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            try {
                PreparedStatement check = con.prepareStatement("select * from users where name=? and username=? and password=? and utype=?"); 
                check.setString(1,name);
                check.setString(2,username);
                check.setString(3,password);
                check.setString(4,usertype);
                rs = check.executeQuery(); 
                 if (rs.next()) { 
                    JOptionPane.showMessageDialog(this,"user already exists");
                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                         } 
                 else {
                    pst=con.prepareStatement("insert into users(name,username,password,utype)values(?,?,?,?)");
                    pst.setString(1,name);
                    pst.setString(2,username);
                    pst.setString(3,password);
                    pst.setString(4,usertype);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"user added successfully");

                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                    this.setVisible(false);
                    new login().setVisible(true);
                     }
        } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtutypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtutypeKeyPressed
            String name = txtname.getText();
            String username = txtusername.getText();
            String password =Arrays.toString(txtpassword.getPassword());
            String usertype = txtutype.getSelectedItem().toString();
            
            if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            try {
                PreparedStatement check = con.prepareStatement("select * from users where name=? and username=? and password=? and utype=?"); 
                check.setString(1,name);
                check.setString(2,username);
                check.setString(3,password);
                check.setString(4,usertype);
                rs = check.executeQuery(); 
                 if (rs.next()) { 
                    JOptionPane.showMessageDialog(this,"user already exists");
                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                         } 
                 else {
                    pst=con.prepareStatement("insert into users(name,username,password,utype)values(?,?,?,?)");
                    pst.setString(1,name);
                    pst.setString(2,username);
                    pst.setString(3,password);
                    pst.setString(4,usertype);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"user added successfully");

                    txtname.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtutype.setSelectedIndex(0);
                    txtname.requestFocus();
                    this.setVisible(false);
                    new login().setVisible(true);
                     }
        } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_txtutypeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new user().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JComboBox<String> txtutype;
    // End of variables declaration//GEN-END:variables
}
